version: '3.7'

# Volumes
volumes:
  db_data:
    name: db_data
  screenrpa_data:
    name: screenrpa_data

services:
  db:
    image: postgres
    container_name: ${DOCKERNAME_PREFIX}db
    restart: always
    env_file: ./.env
    hostname: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

  screenrpa:
    image: amartinezrojas/screenrpa:v2
    container_name: ${DOCKERNAME_PREFIX}screenrpa
    restart: unless-stopped
    env_file: ./.env
    command: tail -F anything
    volumes:
      - screenrpa_data:/screenrpa
    networks:
      - db_network
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - screenrpa
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 