version: '3.7'

# Volumes
volumes:
  db_data:
    name: ${DOCKERNAME}db_data
  screenrpa_data:
    name: ${DOCKERNAME}screenrpa_data

services:
  db:
    image: postgres
    container_name: ${DOCKERNAME}screenrpa-db-dev
    restart: always
    env:
      POSTGRES_USER: ${secrets.POSTGRES_USER}
      POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWORD}
      POSTGRES_DB: ${secrets.POSTGRES_DB}
      DB_NAME: ${secrets.DB_NAME}
      DB_HOST: ${secrets.DB_HOST}
      DB_PORT: ${secrets.DB_PORT}
      DB_USER: ${secrets.DB_USER}
      DB_PASSWORD: ${secrets.DB_PASSWORD}
      EMAIL_HOST_USER: ${secrets.EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${secrets.EMAIL_HOST_PASSWORD}
    hostname: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

  screen-rpa:
    container_name: ${DOCKERNAME}screenrpa-nvidia-dev
    restart: unless-stopped
    env_file: ./.env
    command: tail -F anything
    build:
      context: ../.
      dockerfile: ./docker/nvidia.Dockerfile
      args:
        branch: ${BRANCH_DOCKER}
        target: dev
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - screenrpa_data:/screenrpa
    networks:
      - db_network
      - web_network

  nginx:
    container_name: screnrpa-nginx-dev
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - screen-rpa
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 