# Volumes
volumes:
  db_data:
    name: db_data
  screenrpa_exp_data:
    name: screenrpa_exp_data
  screenrpa_repro_data:
    name: screenrpa_repro_data

services:
  db:
    image: postgres:16
    container_name: screenrpa-db-dev
    restart: always
    env_file: ./.env
    hostname: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

  screenrpa:
    container_name: screenrpa-dev
    restart: unless-stopped
    env_file: ./.env
    image: "tunixr/screenrpa"
    command: tail -F anything
    ports:
      - "8000:8000"
    volumes:
      - screenrpa_exp_data:/screenrpa/media
      - screenrpa_repro_data:/reproducibility
    networks:
      - db_network
      - web_network
    depends_on:
      - db

  nginx:
    container_name: screenrpa-nginx-dev
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - screenrpa
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 